version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:23.0.2
    steps:
      - run:
          name: Setup Git LFS authentication
          command: |
            # Validate that GITHUB_TOKEN is set
            if [ -z "$GITHUB_TOKEN" ]; then
              echo "Error: GITHUB_TOKEN environment variable is not set"
              echo "Please add GITHUB_TOKEN to your CircleCI project environment variables"
              exit 1
            fi
            
            # Install Git LFS if not already available
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install git-lfs
            
            # Configure Git LFS authentication using GitHub token
            git config --global credential.helper store
            echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > ~/.git-credentials
            
            # Alternative SSH-based authentication (uncomment if using SSH keys):
            # mkdir -p ~/.ssh
            # echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
            # chmod 600 ~/.ssh/id_rsa
            # ssh-keyscan github.com >> ~/.ssh/known_hosts
            # git config --global url."git@github.com:".insteadOf "https://github.com/"
            
            # Initialize Git LFS
            git lfs install
      - checkout:
          path: .
          submodules: false
      - run:
          name: Initialize submodules with LFS
          command: |
            # Ensure Git LFS is configured for submodules
            git config --global credential.helper store
            echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > ~/.git-credentials
            
            # Debug: Check Git LFS configuration
            echo "Git LFS version:"
            git lfs version
            
            echo "Git credential configuration:"
            git config --global --list | grep credential
            
            # Initialize and update submodules with LFS support
            git submodule update --init
            
            # Debug: Check if LFS files were downloaded
            echo "Checking for LFS files in submodules:"
            find . -name "*.png" -exec git lfs ls-files {} \; 2>/dev/null || echo "No LFS files found or LFS not tracking PNG files"
      - run:
          name: Install DAML
          command: |
            curl -sSL https://get.daml.com/ | sh -s 3.3.0-snapshot.20250507.0
            echo 'export PATH=$HOME/.daml/bin:$PATH' >> "$BASH_ENV"
      - run:
          name: Install Node.js
          command: |
            # Download and install nvm:
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash

            # in lieu of restarting the shell
            \. "$HOME/.nvm/nvm.sh"

            # Download and install Node.js:
            nvm install 22.16.0

            # Update PATH for subsequent steps:
            echo 'export NVM_DIR="$HOME/.nvm"' >> "$BASH_ENV"
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> "$BASH_ENV"
            echo 'export PATH="$NVM_DIR/versions/node/v22.16.0/bin:$PATH"' >> "$BASH_ENV"

            # Verify the Node.js version:
            node -v # Should print "v22.16.0".
            nvm current # Should print "v22.16.0".

            # Verify npm version:
            npm -v # Should print "10.9.2".
      - run:
          name: Build and Test
          command: npm run test
      - run:
          name: Install and Build Scripts
          command: |
            cd scripts
            npm install
            npm run build
      - run:
          name: Install and Build UI
          command: |
            cd ui
            npm install
            npm run build


workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
